rootProject.name = "Wonderland"
include(":app")
include(":domain")
include(":data")
include(":common:base")
include(":common:model")
include(":common:auth")
include(":common:component")
include(":common:resource")
include(":feature:splash")
include(":feature:onboarding")
include(":feature:festival")
