rootProject.name = "Wonderland"
include(":app")
include(":domain")
include(":data")
include(":remote")
include(":cache")
include(":feature-onboarding")
include(":core-ui")
include(":common:component")
include(":common:resource")
