object Module {
    const val App = ":app"
    const val Data = ":data"
    const val Domain = ":domain"
    const val CommonBase = ":common:base"
    const val CommonModel = ":common:model"
    const val CommonAuth = ":common:auth"
    const val CommonComponent = ":common:component"
    const val CommonResource = ":common:resource"
    const val FeatureSplash = ":feature:splash"
    const val FeatureOnboarding = ":feature:onboarding"
    const val FeatureHome = ":feature:home"
    const val FeatureSearch = ":feature:search"
    const val FeatureCalendar = ":feature:calendar"
    const val FeatureMy = ":feature:my"
    const val FeatureFestival = ":feature:festival"
}
